### ISSUE TITLE
Link broken a NFT created on the testnet

### ISSUE THREAD

**Issue by parkerburchett** [calvincs/xrpl-nft-creator#2]
I'm trying to find one of the NFTs you created on the testnet. 

From the example meta.json file in the README.txt
````
  "details": {
      "title": "Big Buck Bunny",
      "description": "When Big Bucks day gets turned upside down by the loss of his favorite butterflies via some rotten rodents, he takes to the offensive to avenge his friends. ...",
      "cover": "bunny.png",
      "link": "bunny.mp4",
      "legal": "The works contained in this package are protected by U.S. and International copyright laws\nCreative Commons Attribution 3.0 license\n(c) copyright 2008, Blender Foundation / www.bigbuckbunny.org",
      "NFTWalletAddress": "rPu3t9CND35sm2waACwKhABtAZhr9g3KW8",
      "NFTWalletXAddress": "XVkwcJoq3RzAP6jcNr6krmPJCHgTWjA4C4BZ4PmeQk7uN4p"
  },
````

When I look for the NFTWalletAddress : "rPu3t9CND35sm2waACwKhABtAZhr9g3KW8" 

https://testnet.xrpl.org/accounts/rPu3t9CND35sm2waACwKhABtAZhr9g3KW8 

I get an "Account not found" error. I get the same error for any of the other addresses when I look them up on a XRP block explorer.

I'm wondering if there are any example NFTs that are on the testnet I could look up.

**Comment by calvincs** [comment]
I created an explorer thats running on the testnet you can use: https://nft.xmpl.cloud/
Its using the following codebase: https://github.com/calvincs/xrpl-account-index

Updates approx every 30 min.

**Comment by calvincs** [comment]
Let me know if you have questions :-)

**Comment by parkerburchett** [comment]
Dude this project is an absolute lifesaver. It just existing is saving me so much time. 

How did you manage to get the IPFS location into the domain field? Like what encoding did you use?

**Comment by calvincs** [comment]
You can also use this: https://index.xmpl.cloud/

Updating the wallet: https://github.com/calvincs/xrpl-nft-creator/blob/main/index.js#L321
Building the xnft object for the domain field: https://github.com/calvincs/xrpl-nft-creator/blob/main/index.js#L541
Passing the values into the function: https://github.com/calvincs/xrpl-nft-creator/blob/main/index.js#L859

**Comment by calvincs** [comment]
Let me know if you have more questions, otherwise Ill close this out.
